# Generated by Django 3.0.3 on 2020-09-09 07:29

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название Спота')),
                ('description', models.TextField(default='Дефолтное описание спота...', verbose_name='Короткое описание')),
                ('features', tinymce.models.HTMLField(default='Дефолтное описание фитч спота...', verbose_name='Длинное описание')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Споты',
                'verbose_name_plural': 'Спот',
            },
        ),
        migrations.CreateModel(
            name='MainImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='main_images/', verbose_name='Верхняя картинка')),
                ('spot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='spots.Spot', verbose_name='Спот')),
            ],
            options={
                'verbose_name': 'Главное изображение',
                'verbose_name_plural': 'Главные изображения',
            },
        ),
        migrations.CreateModel(
            name='FeatureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='features_images/', verbose_name='Изображение фитч')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='spots.Spot', verbose_name='Спот')),
            ],
            options={
                'verbose_name': 'Изображение фитч спота',
                'verbose_name_plural': 'Изображения фитч спота',
            },
        ),
    ]
