# Generated by Django 3.0.3 on 2020-10-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spot',
            options={'verbose_name': 'Спот', 'verbose_name_plural': 'Споты'},
        ),
        migrations.AddField(
            model_name='spot',
            name='inst',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ссылка на инсту'),
        ),
        migrations.AddField(
            model_name='spot',
            name='vk',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ссылка на вк'),
        ),
    ]
